name: Use Custom Action

on:
  push:
    branches: [ main ]

jobs:
  run-custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Greeting Custom Action
        uses: ./.github/actions/greeting-action
        with:
          student-name: Rana